### ISSUE TITLE
SpotifyOauthError

### ISSUE THREAD

**Issue by laminthurein1411** [jayme-github/spotify-backup#1]
spotify.py has No client_secret. Forget 
```typescript
CLIENT_SECRET= os.getenv()
```

**Comment by jayme-github** [comment]
I don't understand what you're saying, sorry. Could you please elaborate?

The client ID and secret need to be provided via the environment variables `SPOTIPY_CLIENT_ID` and `SPOTIPY_CLIENT_SECRET`.
